
integration:
  iflytek:
    tts: https://api.xfyun.cn/v1/service

iflytek:
  appid: 5d5b6c2f
  api-key: 56b8cc3fc12ff0db5be5c4d392b6ab0a
  # 音频编码(raw合成的音频格式pcm、wav,lame合成的音频格式MP3)
  aue: raw
  # 采样率
  auf: audio/L16;rate=16000
  # 语速（取值范围0-100）
  speed: 50
  # 音量（取值范围0-100）
  volume: 50
  # 音调（取值范围0-100）
  pitch: 50
  # 发音人（登陆开放平台https://www.xfyun.cn/后--我的应用（必须为webapi类型应用）--添加在线语音合成（已添加的不用添加）--发音人管理---添加发音人--修改发音人参数）
  voice-name: xiaoyan
  # 引擎类型
  engine-type: intp65
  # 文本类型（webapi是单次只支持1000个字节，具体看您的编码格式，计算一下具体支持多少文字）
  text-type: text